### ISSUE TITLE
Search missing searches all episodes, not just monitored

### ISSUE THREAD

**Issue by Moonlight63** [Drapersniper/Qbitrr#64]
Title pretty much says it all. I wanted to set this up in the hopes of making things more automated. In particular, if a download failed and left sonarr with an episode missing from disk, I wanted it to be able to automatically search for the missing episode. Basically, periodically do a "Search all monitored" command. I did very little modification to the config, and related to searrches, all I did was change SearchBySeries to false, as that seemed to stop searches from happening at all. I also enabled SearchAgainOnSearchCompletion. Full EntrySearch section below. As soon as I did that, and run the container, I saw that it was indeed running searches, but it was running searches on EVERYTHING. Every single episode on every single series, including unmonitored ones. How can I make this only search for 'monitored' episodes?
```toml
[Sonarr-TV.EntrySearch]
# All these settings depends on SearchMissing being True and access to the Servarr database file.

# Should search for Missing files?
SearchMissing = true

# Should search for specials episodes? (Season 00)
AlsoSearchSpecials = false

# Maximum allowed Searches at any one points (I wouldn't recommend settings this too high)
# Sonarr has a hardcoded cap of 3 simultaneous tasks
SearchLimit = 5

# Servarr Datapath file path
# This is required for any of the search functionality to work
# The only exception for this is the "ReSearch" setting as that is done via an API call.
DatabaseFile = "/databases/sonarr.db"

# It will order searches by the year the EPISODE was first aired
SearchByYear = true

# First year to search; Remove this field to set it to the current year.
#StartYear = 2022

# Last Year to Search
LastYear = 1980

# Reverse search order (Start searching in "LastYear" and finish in "StartYear")
SearchInReverse = false

# Delay between request searches in seconds
SearchRequestsEvery = 60 #1800

# Search movies which already have a file in the database in hopes of finding a better quality version.
DoUpgradeSearch = false

# Do a quality unmet search for existing entries.
QualityUnmetSearch = false

# Once you have search all files on your specified year range restart the loop and search again.
SearchAgainOnSearchCompletion = true

# Search by series instead of by episode
SearchBySeries = false

# Prioritize Today's releases (Similar effect as RSS Sync, where it searches today's release episodes first, only works on Sonarr).
PrioritizeTodaysReleases = true

```
